info:
    app:
        description: Cart System for Online Shop - University of Antioquia
        name: Cart MicroService
        version: 1.0.0
management:
    endpoints:
        web:
            base-path: /
server:
    port: 8090
    servlet:
        context-path: /Cart
spring:
    kafka:
        bootstrap-servers: ${KAFKA_BROKERS}
        consumer:
            auto-offset-reset: latest
            group-id: CheckedOut-consumers
            properties:
                spring:
                    json:
                        trusted:
                            packages: sample.kafka
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
#        properties:
#            sasl:
#                jaas:
#                    config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
#                mechanism: SCRAM-SHA-256
#            security:
#                protocol: SASL_SSL

topic:
    CheckedOut